apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-quota
  namespace: test1
spec:
  hard:
    pods: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-quota
  namespace: test2
spec:
  hard:
    pods: "10"