apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: small-fast
  namespace: small-fast
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "67"
        autoscaling.knative.dev/window: "1m"
        autoscaling.knative.dev/scale-down-delay: "5m"
        autoscaling.knative.dev/target-burst-capacity: "-1"
        autoscaling.knative.dev/initial-scale: "0"
    spec:
      containerConcurrency: 1
      containers:
      - image: ghcr.io/titi622/small-fast:v1
        env:
        - name: COLD_SLEEP_SEC
          value: "0.5"
        ports:
        - containerPort: 8090
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8090
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "1"
            memory: "256Mi"
